import type { NextPage } from 'next'
import Head from 'next/head'
<<<<<<< HEAD
=======
import styles from '../styles/Home.module.css'

>>>>>>> de5b7a57e6bb5de28ab5344a0ba7492ad1c5bac0

import styled from "styled-components";
import DvdAnimation from "../components/DVD";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Office Supply</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <DvdAnimation>
      </DvdAnimation>
    </div>
  )
}

export default Home
