import type { NextPage } from 'next'
import Head from 'next/head'

import styled from "styled-components";
import DvdAnimation from "../components/DVD";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Office Supply</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <DvdAnimation>
      </DvdAnimation>
    </div>
  )
}

export default Home
