import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import DvdAnimation from "../components/DVD";
import Dvdbox from '../components/DVDCanvas';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Office Supply</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Dvdbox>
      <DvdAnimation>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
      </main>

      <footer className={styles.footer}>
      </footer>
      </DvdAnimation>
      </Dvdbox>
    </div>
  )
}

export default Home
